version: "3.8"

services:
  tumlab_apps:
    image: bilinguismotalentum/tumlab-apps:1.3.0
    container_name: tumlab_apps
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
      - /tumlab/syncthing/agent.config:/usr/share/nginx/html/info/agent.json
    ports:
      - ${APP_PORT:-80}:80
